name: docker-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  FOLDER: template
  OLS_VERSION: 1.8.1

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        # PHP_VERSION: [lsphp74, lsphp80, lsphp81, lsphp82, lsphp83]
        PHP_VERSION: [lsphp83]
        TAG: [latest]
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and push
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          cd ${{ env.FOLDER }}
          bash build.sh --ols ${{ env.OLS_VERSION }} --php ${{ matrix.PHP_VERSION }} --tag "${{ matrix.TAG }}" --push
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  