name: docker-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FOLDER: template
  OLS_VERSION: 1.8.1

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        # PHP_VERSION: [lsphp74, lsphp80, lsphp81, lsphp82, lsphp83]
        PHP_VERSION: [lsphp83]
        TAG: [latest]
    steps:
      - uses: actions/checkout@v2
      # - name: Docker build and push
      #   run: |
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #     cd ${{ env.FOLDER }}
      #     bash build.sh --ols ${{ env.OLS_VERSION }} --php ${{ matrix.PHP_VERSION }} --tag "${{ matrix.TAG }}" --push
      #   env: 
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        # id: buildx
        uses: docker/setup-buildx-action@v3
          # with:
          #   install: true
      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Multi architecture build and push

      - name: Build & Push Image
        run: |
          cd ${{ env.FOLDER }}
          docker buildx build --build-arg OLS_VERSION=${{ env.OLS_VERSION }} --build-arg PHP_VERSION=${{ matrix.PHP_VERSION }} --file ./Dockerfile  --push --tag k4mrul/ols:${{ env.OLS_VERSION }}-${{ matrix.PHP_VERSION }} --platform=linux/arm64,linux/amd64 .
          # bash build.sh --ols ${{ env.OLS_VERSION }} --php ${{ matrix.PHP_VERSION }} --tag "${{ matrix.TAG }}" --push
      
  